name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          git config --global user.email "malin.malliya.wadu@gmail.com"
          git config --global user.name "malinmalliyawadu"

      - run: |
          npm i
          npm run build
          npm run deploy
